# Generated by Django 5.2 on 2025-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='APELLIDO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
