# Generated by Django 5.2 on 2025-04-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_estudiantes_apellido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estudiantes',
        ),
    ]
